### ISSUE TITLE
Feature request: store passwords with optional nickname

### ISSUE THREAD

**Issue by rugglcon** [ChristopherNugent/Locksmith#16]
This is a great native password generator, but it would be great if you could save those passwords to disk with an optional nickname. If you would like this feature implemented, I could look at it in a couple weeks when I'm done with school (for good, thank god).

Let me know what you think, and if you have any ideas on what exactly you would want for this.

**Comment by ChristopherNugent** [comment]
I know the feeling, I'm almost done with my degree as well.

For saving to disk, were you thinking just something like a dump to a text file or interfacing with something like a keychain?

**Comment by rugglcon** [comment]
The keychain probably makes more sense since it's made for elementary, although it could also use a sqlite db pretty easily.

**Comment by ChristopherNugent** [comment]
I'd rather not take the responsibility of managing people's passwords, at least not within the context of Locksmith. I'll look into adding it to the keychain, but I think it needs a good elementary specific GUI first.

In the interim, I'm planning to add a "Copy to Clipboard" button which should help smooth usage a little bit.

**Comment by ChristopherNugent** [comment]
@rugglcon I think it may be useful to build an elementary specific keychain GUI, if you're interested I could use some help on that.
